### ISSUE TITLE
Exception in wrapper_func  AttributeError: 'NotificationSession' object has no attribute 'framer'

### ISSUE THREAD

**Issue by gitforwebwork** [namecoin/electrum-nmc#148]
I am getting lots or errors when executing: ./run_electrum_nmc

E/i | interface.[electrum-nmc.le-space.de:50002] | Exception in wrapper_func: AttributeError("'NotificationSession' object has no attribute 'framer'")
Traceback (most recent call last):
  File "/home/user/GIT/electrum-nmc/electrum_nmc/util.py", line 901, in wrapper
    return await func(*args, **kwargs)
  File "/home/user/GIT/electrum-nmc/electrum_nmc/interface.py", line 334, in wrapper_func
    return await func(self, *args, **kwargs)
  File "/home/user/GIT/electrum-nmc/electrum_nmc/interface.py", line 352, in run
    ssl_context = await self._get_ssl_context()
  File "/home/user/GIT/electrum-nmc/electrum_nmc/interface.py", line 317, in _get_ssl_context
    await self._try_saving_ssl_cert_for_first_time(ca_sslc)
  File "/home/user/GIT/electrum-nmc/electrum_nmc/interface.py", line 274, in _try_saving_ssl_cert_for_first_time
    ca_signed = await self.is_server_ca_signed(ca_ssl_context)
  File "/home/user/GIT/electrum-nmc/electrum_nmc/interface.py", line 264, in is_server_ca_signed
    await self.open_session(ca_ssl_context, exit_early=True)
  File "/home/user/GIT/electrum-nmc/electrum_nmc/interface.py", line 453, in open_session
    ssl=sslc, proxy=self.proxy) as session:
  File "/home/user/.local/lib/python3.7/site-packages/aiorpcx/rawsocket.py", line 166, in __aenter__
    _transport, protocol = await self.create_connection()
  File "/home/user/GIT/electrum-nmc/electrum_nmc/interface.py", line 185, in create_connection
    return await super().create_connection()
  File "/home/user/.local/lib/python3.7/site-packages/aiorpcx/rawsocket.py", line 163, in create_connection
    self.protocol_factory, self.host, self.port, **self.kwargs)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 986, in create_connection
    ssl_handshake_timeout=ssl_handshake_timeout)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1014, in _create_connection_transport
    await waiter
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 192, in feed_ssldata
    self._handshake_cb(None)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 647, in _on_handshake_complete
    self._app_protocol.connection_made(self._app_transport)
  File "/home/user/.local/lib/python3.7/site-packages/aiorpcx/rawsocket.py", line 81, in connection_made
    self.session = self.session_factory(self)
  File "/home/user/GIT/electrum-nmc/electrum_nmc/interface.py", line 87, in __init__
    self.framer.max_size = 20000000
AttributeError: 'NotificationSession' object has no attribute 'framer'

E/i | interface.[electrum-nmc.le-space.de:50002] | Exception in wrapper_func: AttributeError("'NotificationSession' object has no attribute 'framer'")
Traceback (most recent call last):
  File "/home/user/GIT/electrum-nmc/electrum_nmc/util.py", line 901, in wrapper
    return await func(*args, **kwargs)
  File "/home/user/GIT/electrum-nmc/electrum_nmc/interface.py", line 334, in wrapper_func
    return await func(self, *args, **kwargs)
  File "/home/user/GIT/electrum-nmc/electrum_nmc/interface.py", line 352, in run
    ssl_context = await self._get_ssl_context()
  File "/home/user/GIT/electrum-nmc/electrum_nmc/interface.py", line 317, in _get_ssl_context
    await self._try_saving_ssl_cert_for_first_time(ca_sslc)
  File "/home/user/GIT/electrum-nmc/electrum_nmc/interface.py", line 274, in _try_saving_ssl_cert_for_first_time
    ca_signed = await self.is_server_ca_signed(ca_ssl_context)
  File "/home/user/GIT/electrum-nmc/electrum_nmc/interface.py", line 264, in is_server_ca_signed
    await self.open_session(ca_ssl_context, exit_early=True)
  File "/home/user/GIT/electrum-nmc/electrum_nmc/interface.py", line 453, in open_session
    ssl=sslc, proxy=self.proxy) as session:
  File "/home/user/.local/lib/python3.7/site-packages/aiorpcx/rawsocket.py", line 166, in __aenter__
    _transport, protocol = await self.create_connection()
  File "/home/user/GIT/electrum-nmc/electrum_nmc/interface.py", line 185, in create_connection
    return await super().create_connection()
  File "/home/user/.local/lib/python3.7/site-packages/aiorpcx/rawsocket.py", line 163, in create_connection
    self.protocol_factory, self.host, self.port, **self.kwargs)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 986, in create_connection
    ssl_handshake_timeout=ssl_handshake_timeout)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1014, in _create_connection_transport
    await waiter
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 192, in feed_ssldata
    self._handshake_cb(None)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 647, in _on_handshake_complete
    self._app_protocol.connection_made(self._app_transport)
  File "/home/user/.local/lib/python3.7/site-packages/aiorpcx/rawsocket.py", line 81, in connection_made
    self.session = self.session_factory(self)
  File "/home/user/GIT/electrum-nmc/electrum_nmc/interface.py", line 87, in __init__
    self.framer.max_size = 20000000
AttributeError: 'NotificationSession' object has no attribute 'framer'

E/i | interface.[ulrichard.ch:50006] | Exception in wrapper_func: AttributeError("'NotificationSession' object has no attribute 'framer'")
Traceback (most recent call last):
  File "/home/user/GIT/electrum-nmc/electrum_nmc/util.py", line 901, in wrapper
    return await func(*args, **kwargs)
  File "/home/user/GIT/electrum-nmc/electrum_nmc/interface.py", line 334, in wrapper_func
    return await func(self, *args, **kwargs)
  File "/home/user/GIT/electrum-nmc/electrum_nmc/interface.py", line 352, in run
    ssl_context = await self._get_ssl_context()
  File "/home/user/GIT/electrum-nmc/electrum_nmc/interface.py", line 317, in _get_ssl_context
    await self._try_saving_ssl_cert_for_first_time(ca_sslc)
  File "/home/user/GIT/electrum-nmc/electrum_nmc/interface.py", line 274, in _try_saving_ssl_cert_for_first_time
    ca_signed = await self.is_server_ca_signed(ca_ssl_context)
  File "/home/user/GIT/electrum-nmc/electrum_nmc/interface.py", line 264, in is_server_ca_signed
    await self.open_session(ca_ssl_context, exit_early=True)
  File "/home/user/GIT/electrum-nmc/electrum_nmc/interface.py", line 453, in open_session
    ssl=sslc, proxy=self.proxy) as session:
  File "/home/user/.local/lib/python3.7/site-packages/aiorpcx/rawsocket.py", line 166, in __aenter__
    _transport, protocol = await self.create_connection()
  File "/home/user/GIT/electrum-nmc/electrum_nmc/interface.py", line 185, in create_connection
    return await super().create_connection()
  File "/home/user/.local/lib/python3.7/site-packages/aiorpcx/rawsocket.py", line 163, in create_connection
    self.protocol_factory, self.host, self.port, **self.kwargs)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 986, in create_connection
    ssl_handshake_timeout=ssl_handshake_timeout)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1014, in _create_connection_transport
    await waiter
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 192, in feed_ssldata
    self._handshake_cb(None)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 647, in _on_handshake_complete
    self._app_protocol.connection_made(self._app_transport)
  File "/home/user/.local/lib/python3.7/site-packages/aiorpcx/rawsocket.py", line 81, in connection_made
    self.session = self.session_factory(self)
  File "/home/user/GIT/electrum-nmc/electrum_nmc/interface.py", line 87, in __init__
    self.framer.max_size = 20000000
AttributeError: 'NotificationSession' object has no attribute 'framer'

E/i | interface.[ulrichard.ch:50006] | Exception in wrapper_func: AttributeError("'NotificationSession' object has no attribute 'framer'")
Traceback (most recent call last):
  File "/home/user/GIT/electrum-nmc/electrum_nmc/util.py", line 901, in wrapper
    return await func(*args, **kwargs)
  File "/home/user/GIT/electrum-nmc/electrum_nmc/interface.py", line 334, in wrapper_func
    return await func(self, *args, **kwargs)
  File "/home/user/GIT/electrum-nmc/electrum_nmc/interface.py", line 352, in run
    ssl_context = await self._get_ssl_context()
  File "/home/user/GIT/electrum-nmc/electrum_nmc/interface.py", line 317, in _get_ssl_context
    await self._try_saving_ssl_cert_for_first_time(ca_sslc)
  File "/home/user/GIT/electrum-nmc/electrum_nmc/interface.py", line 274, in _try_saving_ssl_cert_for_first_time
    ca_signed = await self.is_server_ca_signed(ca_ssl_context)
  File "/home/user/GIT/electrum-nmc/electrum_nmc/interface.py", line 264, in is_server_ca_signed
    await self.open_session(ca_ssl_context, exit_early=True)
  File "/home/user/GIT/electrum-nmc/electrum_nmc/interface.py", line 453, in open_session
    ssl=sslc, proxy=self.proxy) as session:
  File "/home/user/.local/lib/python3.7/site-packages/aiorpcx/rawsocket.py", line 166, in __aenter__
    _transport, protocol = await self.create_connection()
  File "/home/user/GIT/electrum-nmc/electrum_nmc/interface.py", line 185, in create_connection
    return await super().create_connection()
  File "/home/user/.local/lib/python3.7/site-packages/aiorpcx/rawsocket.py", line 163, in create_connection
    self.protocol_factory, self.host, self.port, **self.kwargs)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 986, in create_connection
    ssl_handshake_timeout=ssl_handshake_timeout)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1014, in _create_connection_transport
    await waiter
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 192, in feed_ssldata
    self._handshake_cb(None)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 647, in _on_handshake_complete
    self._app_protocol.connection_made(self._app_transport)
  File "/home/user/.local/lib/python3.7/site-packages/aiorpcx/rawsocket.py", line 81, in connection_made
    self.session = self.session_factory(self)
  File "/home/user/GIT/electrum-nmc/electrum_nmc/interface.py", line 87, in __init__
    self.framer.max_size = 20000000
AttributeError: 'NotificationSession' object has no attribute 'framer'

E/i | interface.[nmc.bitcoins.sk:50002] | Exception in wrapper_func: AttributeError("'NotificationSession' object has no attribute 'framer'")
Traceback (most recent call last):
  File "/home/user/GIT/electrum-nmc/electrum_nmc/util.py", line 901, in wrapper
    return await func(*args, **kwargs)
  File "/home/user/GIT/electrum-nmc/electrum_nmc/interface.py", line 334, in wrapper_func
    return await func(self, *args, **kwargs)
  File "/home/user/GIT/electrum-nmc/electrum_nmc/interface.py", line 357, in run
    await self.open_session(ssl_context)
  File "/home/user/GIT/electrum-nmc/electrum_nmc/interface.py", line 453, in open_session
    ssl=sslc, proxy=self.proxy) as session:
  File "/home/user/.local/lib/python3.7/site-packages/aiorpcx/rawsocket.py", line 166, in __aenter__
    _transport, protocol = await self.create_connection()
  File "/home/user/GIT/electrum-nmc/electrum_nmc/interface.py", line 185, in create_connection
    return await super().create_connection()
  File "/home/user/.local/lib/python3.7/site-packages/aiorpcx/rawsocket.py", line 163, in create_connection
    self.protocol_factory, self.host, self.port, **self.kwargs)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 986, in create_connection
    ssl_handshake_timeout=ssl_handshake_timeout)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1014, in _create_connection_transport
    await waiter
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 192, in feed_ssldata
    self._handshake_cb(None)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 647, in _on_handshake_complete
    self._app_protocol.connection_made(self._app_transport)
  File "/home/user/.local/lib/python3.7/site-packages/aiorpcx/rawsocket.py", line 81, in connection_made
    self.session = self.session_factory(self)
  File "/home/user/GIT/electrum-nmc/electrum_nmc/interface.py", line 87, in __init__
    self.framer.max_size = 20000000
AttributeError: 'NotificationSession' object has no attribute 'framer'

E/i | interface.[nmc.bitcoins.sk:50002] | Exception in wrapper_func: AttributeError("'NotificationSession' object has no attribute 'framer'")
Traceback (most recent call last):
  File "/home/user/GIT/electrum-nmc/electrum_nmc/util.py", line 901, in wrapper
    return await func(*args, **kwargs)
  File "/home/user/GIT/electrum-nmc/electrum_nmc/interface.py", line 334, in wrapper_func
    return await func(self, *args, **kwargs)
  File "/home/user/GIT/electrum-nmc/electrum_nmc/interface.py", line 357, in run
    await self.open_session(ssl_context)
  File "/home/user/GIT/electrum-nmc/electrum_nmc/interface.py", line 453, in open_session
    ssl=sslc, proxy=self.proxy) as session:
  File "/home/user/.local/lib/python3.7/site-packages/aiorpcx/rawsocket.py", line 166, in __aenter__
    _transport, protocol = await self.create_connection()
  File "/home/user/GIT/electrum-nmc/electrum_nmc/interface.py", line 185, in create_connection
    return await super().create_connection()
  File "/home/user/.local/lib/python3.7/site-packages/aiorpcx/rawsocket.py", line 163, in create_connection
    self.protocol_factory, self.host, self.port, **self.kwargs)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 986, in create_connection
    ssl_handshake_timeout=ssl_handshake_timeout)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1014, in _create_connection_transport
    await waiter
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 192, in feed_ssldata
    self._handshake_cb(None)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 647, in _on_handshake_complete
    self._app_protocol.connection_made(self._app_transport)
  File "/home/user/.local/lib/python3.7/site-packages/aiorpcx/rawsocket.py", line 81, in connection_made
    self.session = self.session_factory(self)
  File "/home/user/GIT/electrum-nmc/electrum_nmc/interface.py", line 87, in __init__
    self.framer.max_size = 20000000
AttributeError: 'NotificationSession' object has no attribute 'framer'

**Comment by JeremyRand** [comment]
Hi, thanks for reporting this bug.  It looks like upstream Electrum upgraded their `aiorpcx` dependency, which introduced a refactor that breaks Electrum-NMC's AuxPoW patches.  I've checked with Neil, and I think this should be fairly easy to fix.

Just to verify, you're seeing this with `master` branch, and the `nc3.3.6.1` branch is unaffected, right?

**Comment by gitforwebwork** [comment]
Thanks for finding the issue and fixing it so fast! :+1:
