### ISSUE TITLE
\electrum_nmc-3.2.2-py3.5.egg - Not Connected 

### ISSUE THREAD

**Issue by almansoori570** [namecoin/electrum-nmc#15]
Traceback
Traceback (most recent call last):
  File "site-packages\electrum_nmc-3.2.2-py3.5.egg\electrum_nmc\util.py", line 835, in run_with_except_hook
  File "threading.py", line 862, in run
  File "C:\Program Files (x86)\Electrum-NMC\electrum_nmc_plugins\trustedcoin\trustedcoin.py", line 381, in f
    return func(self, *args, **kwargs)
  File "C:\Program Files (x86)\Electrum-NMC\electrum_nmc_plugins\trustedcoin\trustedcoin.py", line 399, in request_billing_info
    .format(billing_address, billing_info['billing_address']))
Exception: unexpected trustedcoin billing address: expected N1S1QpNZWhUuytVeXZx14716CbWCozJAZ3, received 15reDAsabKPMTMF9FkdRqarBUN79uT1eLk
 
Additional information
Electrum version: 3.2.2 
Operating system: Windows-7-6.1.7601-SP1 
Wallet type: 2fa 
Locale: en_US

**Comment by JeremyRand** [comment]
Hi!

It looks like you're using the Trusted Coin service.  I can't find any documentation on whether they support non-Bitcoin cryptocurrencies, other than one reference indicating that they [don't support Bcash](https://www.reddit.com/r/btc/comments/6wf50x/recovering_your_bitcoin_cash_from_a_trustedcoin/).  My guess is that Trusted Coin doesn't support Namecoin on their end, and that you should bring this up with the Trusted Coin people.  If they need any help adding Namecoin support, we're happy to help.

**Comment by JeremyRand** [comment]
Closing in favor of https://github.com/namecoin/electrum-nmc/issues/111
