### ISSUE TITLE
New bug in electrum nmc

### ISSUE THREAD

**Issue by thedevotedone** [namecoin/electrum-nmc#295]
Traceback
Traceback (most recent call last):
  File "electrum_nmc\electrum\gui\qt\uno_list.py", line 292, in configure_selected_item
  File "electrum_nmc\electrum\gui\qt\configure_name_dialog.py", line 49, in show_configure_name
  File "electrum_nmc\electrum\gui\qt\configure_name_dialog.py", line 72, in __init__
  File "electrum_nmc\electrum\names.py", line 203, in format_name_identifier
AttributeError: 'NoneType' object has no attribute 'decode'
 
Additional information
Electrum version: 3.3.10 
Python version: 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)] 
Operating system: Windows-10-10.0.19041-SP0 
Wallet type: standard 
Locale: en_US

**Comment by JeremyRand** [comment]
Hi!  Thanks for the bug report.  It looks like this happened when you tried to reconfigure a name?  Can you tell me anything about the name that you tried to reconfigure?  Was it a `name_new`, by any chance?
