### ISSUE TITLE
Keepkey Domain register AssertionError: None

### ISSUE THREAD

**Issue by marek22k** [namecoin/electrum-nmc#296]
Hello, I am using the wallet with my KeepKey. The KeepKey is up to date. I set it up normally and transferred a small amount to Namecoin. Next I tried to register a name.
What was a little strange is that I was asked for a password (not the password for the KeepKey) because I never set one. I then just clicked "OK". The relevant data was entered and then it appeared that an error had occurred (see below).

Is that up to me? Is that a bug in the program?
I hope it's okay that I made a new issue here.

```
$./electrum-nmc-nc3.3.10-x86_64.AppImage 
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 1107, resource id: 10488252, major code: 40 (TranslateCoords), minor code: 0
Traceback (most recent call last):
  File "/tmp/user/1000/.mount_electrHJYM6o/usr/lib/python3.6/site-packages/electrum_nmc/electrum/gui/qt/configure_name_dialog.py", line 155, in register_and_broadcast
    name_autoregister(identifier.decode('ascii'), value.decode('ascii'), recipient_address)
  File "/tmp/user/1000/.mount_electrHJYM6o/usr/lib/python3.6/site-packages/electrum_nmc/electrum/gui/qt/main_window.py", line 2107, in <lambda>
    return lambda *args: f(method, args, self.password_dialog)
  File "/tmp/user/1000/.mount_electrHJYM6o/usr/lib/python3.6/site-packages/electrum_nmc/electrum/commands.py", line 149, in _run
    result = f(*args, **{'password':password})
  File "/tmp/user/1000/.mount_electrHJYM6o/usr/lib/python3.6/site-packages/electrum_nmc/electrum/commands.py", line 123, in func_wrapper
    return func(*args, **kwargs)
  File "/tmp/user/1000/.mount_electrHJYM6o/usr/lib/python3.6/site-packages/electrum_nmc/electrum/commands.py", line 745, in name_autoregister
    status = self.addtransaction(new_tx)
  File "/tmp/user/1000/.mount_electrHJYM6o/usr/lib/python3.6/site-packages/electrum_nmc/electrum/commands.py", line 123, in func_wrapper
    return func(*args, **kwargs)
  File "/tmp/user/1000/.mount_electrHJYM6o/usr/lib/python3.6/site-packages/electrum_nmc/electrum/commands.py", line 973, in addtransaction
    if not self.wallet.add_transaction(tx.txid(), tx):
  File "/tmp/user/1000/.mount_electrHJYM6o/usr/lib/python3.6/site-packages/electrum_nmc/electrum/address_synchronizer.py", line 203, in add_transaction
    assert tx_hash, tx_hash
AssertionError: None

```

**Comment by JeremyRand** [comment]
Hi!  Thanks for the bug report.  Name operations are not yet supported for hardware wallets.  This is due to missing support for name operations in the firmware.  We intend to submit firmware patches to KeepKey, but haven't had a chance to do it yet.
