### ISSUE TITLE
v4.0.0b0 bug:  ModuleNotFoundError

### ISSUE THREAD

**Issue by maxweisspoker** [namecoin/electrum-nmc#303]
OS: Arch Linux
Python: 3.10

Compiled tag v4.0.0b0 from source:

```
$   for i in dnsdialog dnssubdomaindialog; do
        pyuic5 electrum_nmc/electrum/gui/qt/forms/$i.ui --execute --output=electrum_nmc/electrum/gui/qt/forms/$i.py
        sed -i s/qvalidatedlineedit/.qvalidatedlineedit/ electrum_nmc/electrum/gui/qt/forms/$i.py
     done
$   python contrib/pull_locale
$   python setup.py build
$   python setup.py install --optimize=1 --prefix=/usr
```
    
When I run it, I run into:

```
$ electrum-nmc
E | daemon.Daemon | GUI raised exception: ModuleNotFoundError("No module named 'electrum.gui.qt.forms.configurenamedialog'"). shutting down.
E | __main__ | daemon.run_gui errored
Traceback (most recent call last):
  File "/usr/bin/electrum-nmc", line 388, in <module>
    d.run_gui(config, plugins)
  File "/usr/lib/python3.10/site-packages/electrum_nmc/electrum/daemon.py", line 600, in run_gui
    gui = __import__('electrum.gui.' + gui_name, fromlist=['electrum'])
  File "/usr/lib/python3.10/site-packages/electrum_nmc/electrum/gui/qt/__init__.py", line 56, in <module>
    from .main_window import ElectrumWindow
  File "/usr/lib/python3.10/site-packages/electrum_nmc/electrum/gui/qt/main_window.py", line 82, in <module>
    from .configure_name_dialog import show_configure_name
  File "/usr/lib/python3.10/site-packages/electrum_nmc/electrum/gui/qt/configure_name_dialog.py", line 41, in <module>
    from .forms.configurenamedialog import Ui_ConfigureNameDialog
ModuleNotFoundError: No module named 'electrum.gui.qt.forms.configurenamedialog'
```

**Comment by JeremyRand** [comment]
> OS: Arch Linux Python: 3.10
> 
> Compiled tag v4.0.0b0 from source:
> 
> ```
> $   for i in dnsdialog dnssubdomaindialog; do
>         pyuic5 electrum_nmc/electrum/gui/qt/forms/$i.ui --execute --output=electrum_nmc/electrum/gui/qt/forms/$i.py
>         sed -i s/qvalidatedlineedit/.qvalidatedlineedit/ electrum_nmc/electrum/gui/qt/forms/$i.py
>      done
> $   python contrib/pull_locale
> $   python setup.py build
> $   python setup.py install --optimize=1 --prefix=/usr
> ```

Where did these build instructions come from?
